(display (map (lambda (x) (begin (display x)(+ x 1))) (list 1 2 3 4)))
(newline)
(display (/ -2))
(newline)
(display (string-set! "Hello, World" 2 #\A))
(newline)
(display (string-ref (list->string (cdr (string->list "HHello, World!"))) 1))
(newline)
(display 1)
(newline)
(display (apply (lambda (x y z) (/ x y z)) (list 1 2 3)))
(newline)
